# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen+github@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_edit_markdown_at_content_extension
project_short_description: Jupyterlab extension to save you the scrolling time from
    when you are at markdown file location and open editor and need to scroll to the
    exact place in the file where the content is. This extension opens the editor
    at the place where the content is
python_name: jupyterlab_edit_markdown_at_content_extension
repository: ''
test: true

